# Generated by Django 6.0 on 2025-12-07 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about this subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("lifetime", "Lifetime Access"),
                    ("monthly", "Monthly (Legacy)"),
                    ("quarterly", "Quarterly (Legacy)"),
                    ("yearly", "Yearly (Legacy)"),
                ],
                default="lifetime",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
