# Generated by Django 6.0 on 2025-12-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_subscription_created_at_subscription_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Lifetime Access'", max_length=100, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in ETB", max_digits=10
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what's included"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this pricing option"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order to display (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Pricing",
                "verbose_name_plural": "Subscription Pricing",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
