# Generated by Django 6.0 on 2025-12-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_subscriptionpricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="computersale",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="SoldItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("specs", models.TextField()),
                ("sold_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
                (
                    "computer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_items",
                        to="shop.computersale",
                    ),
                ),
            ],
        ),
    ]
