# Generated by Django 6.0 on 2025-12-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancejob",
            name="computer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_jobs",
                to="shop.computersale",
            ),
        ),
        migrations.AlterField(
            model_name="computersale",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Sold", "Sold"),
                    ("Maintenance", "Maintenance"),
                    ("Reserved", "Reserved"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
