// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0iFXodvmUVZLy8TvieWbJu5P3Oiikd0',
    appId: '1:938486462623:web:a6f01f7346085007134aaa',
    messagingSenderId: '938486462623',
    projectId: 'shoppingapp-niv0415',
    authDomain: 'shoppingapp-niv0415.firebaseapp.com',
    storageBucket: 'shoppingapp-niv0415.firebasestorage.app',
    measurementId: 'G-L1PCN5DLTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28GeylpjFRDnMjSWbfi09hY6woX0Yw1E',
    appId: '1:938486462623:android:b042921d17ccd33e134aaa',
    messagingSenderId: '938486462623',
    projectId: 'shoppingapp-niv0415',
    storageBucket: 'shoppingapp-niv0415.firebasestorage.app',
  );
}
